name: nfc_csem
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  nfc_in_flutter: 2.0.5
  path_provider: 1.6.11
  hive: ^1.4.4+1
  hive_flutter: ^0.3.0+1
  csv: ^4.0.3
  share: ^0.6.5
  flutter_launcher_icons: ^0.8.1
  syncfusion_flutter_charts: ^18.3.44

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.2
  hive_generator: 0.7.1
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "images/csem_app.png"

flutter:
  assets:
    - images/csembr.png

  uses-material-design: true